### ISSUE TITLE
wlroots build error #2

### ISSUE THREAD

**Issue by ghost** [gkisslinux/grepo#36]
I get an error when I try to build wlroots:
```
ninja: job failed: /usr/bin/meson --internal exe --capture backend/drm/pnpids.h --feed /root/.cache/kiss/proc/890479/build/wlroots/pnp.ids -- /root/.cache/kiss/proc/890479/build/wlroots/backend/drm/gen_pnpids.sh
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.62.2', 'console_scripts', 'meson')())
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 271, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 260, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 203, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/meson_exe.py", line 122, in run
    return run_exe(exe)
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/meson_exe.py", line 66, in run_exe
    p = subprocess.Popen(cmd_args, env=child_env, cwd=exe.workdir,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1733, in _execute_child
    self._posix_spawn(args, executable, env, restore_signals,
  File "/usr/lib/python3.10/subprocess.py", line 1678, in _posix_spawn
    self.pid = os.posix_spawn(executable, args, env, **kwargs)
PermissionError: [Errno 13] Permission denied: '/root/.cache/kiss/proc/890479/build/wlroots/backend/drm/gen_pnpids.sh'
ninja: subcommand failed
```
A temporary solution: add `chmod +x backend/drm/gen_pnpids.sh` to the build file (before make)

**Comment by git-bruh** [comment]
Ah perhaps busybox patch doesn't detect the file mode, fixing
